### ISSUE TITLE
Not able to build PulseAudioOSX on MAC 10.6

### ISSUE THREAD

**Issue by Sanjayvi** [zonque/PulseAudioOSX#1]
I have followed all the instructions for building PulseAudioOSX given in the Wiki page but getting following error ...
ld: symbol(s) not found for architecture i386
collect2: ld returned 1 exit status
lipo: can't open input file: /var/tmp//ccnq1YH7.out (No such file or directory)
make[3]: **\* [pacat] Error 1
make[2]: **\* [install] Error 2
make[1]: **\* [install-recursive] Error 1
make: **\* [install] Error 2
Please help me to resolve this issue.

**Comment by zonque** [comment]
On Thu, May 26, 2011 at 9:56 AM, Sanjayvi
reply@reply.github.com
wrote:

> I have followed all the instructions for building PulseAudioOSX given in the Wiki page but getting following error ...
> ld: symbol(s) not found for architecture i386
> collect2: ld returned 1 exit status
> lipo: can't open input file: /var/tmp//ccnq1YH7.out (No such file or directory)
> make[3]: **\* [pacat] Error 1
> make[2]: **\* [install] Error 2
> make[1]: **\* [install-recursive] Error 1
> make: **\* [install] Error 2
> Please help me to resolve this issue.

Please post more of your output, the dump above doesn't show the actual error.

What hardware are you working on? Which steps did you follow?

Daniel

**Comment by muskorv** [comment]
I'm having the exact same issue as Sanjayvi. I followed the steps described here (https://github.com/zonque/PulseAudioOSX/wiki/Building-from-source) and I'm running 10.6.8 on an iMac with a Core 2 Duo processor. 

Some more output, don't know if it helps:

gcc-4.2 -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/opt/local/include -I../src -I../src/modules -I../src/modules -D_THREAD_SAFE -pthread -DPA_ALSA_PATHS_DIR=\"\" -DPA_ALSA_PROFILE_SETS_DIR=\"\"   -I/opt/local/include -O2 -Wall -W -Wextra -pipe -Wno-long-long -Wno-overlength-strings -Wunsafe-loop-optimizations -Wundef -Wformat=2 -Wsign-compare -Wformat-security -Wmissing-include-dirs -Wformat-nonliteral -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Wmissing-noreturn -Wshadow -Wendif-labels -Wcast-align -Wstrict-aliasing -Wwrite-strings -Wno-unused-parameter -ffast-math -Wp,-D_FORTIFY_SOURCE=2 -fno-common -fdiagnostics-show-option -isysroot /Developer/SDKs/MacOSX10.6.sdk -mmacosx-version-min=10.6 -arch i386 -arch x86_64 -c -o pulseaudio-main.o `test -f 'daemon/main.c' || echo './'`daemon/main.c
  CCLD   pulseaudio
ld: warning: in /opt/local/lib/libspeexdsp.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /opt/local/lib/libsndfile.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /opt/local/lib/libjson.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /opt/local/lib/libltdl.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /opt/local/lib/libgdbm.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
Undefined symbols for architecture i386:
  "_lt_dlloader_add", referenced from:
      _pa_ltdl_init in pulseaudio-ltdl-bind-now.o
  "_lt_dlinit", referenced from:
      _pa_ltdl_init in pulseaudio-ltdl-bind-now.o
  "_lt_dlloader_find", referenced from:
      _pa_ltdl_init in pulseaudio-ltdl-bind-now.o
  "_lt_dlpreload_default", referenced from:
      _main in pulseaudio-main.o
  "_lt_dlforeachfile", referenced from:
      _pa_dump_modules in pulseaudio-dumpmodules.o
  "_lt_dlseterror", referenced from:
      _bind_now_find_sym in pulseaudio-ltdl-bind-now.o
      _bind_now_close in pulseaudio-ltdl-bind-now.o
      _bind_now_open in pulseaudio-ltdl-bind-now.o
  "_lt_dlsetsearchpath", referenced from:
      _main in pulseaudio-main.o
  "_lt_dlexit", referenced from:
      _pa_ltdl_done in pulseaudio-ltdl-bind-now.o
ld: symbol(s) not found for architecture i386
collect2: ld returned 1 exit status
lipo: can't open input file: /var/tmp//ccGtgwkg.out (No such file or directory)
make[3]: **\* [pulseaudio] Error 1
make[2]: **\* [install] Error 2
make[1]: **\* [install-recursive] Error 1
make: **\* [install] Error 2

**Comment by zonque** [comment]
Please make sure you used the latest version of the command line using "port" to install the required dependencies. In particular, make sure you built every one of these in its "+universial" variant.

**Comment by muskorv** [comment]
Thanks for replying!

I've upgraded to Lion, Xcode 4.1 and MacPorts 2.0.0 and installed the packages again, following [these instructions](https://github.com/zonque/PulseAudioOSX/wiki/Building-from-source). Still can't get it to compile.

Are there any precompiled binaries available?

arch x86_64 -c -o once_test-once-test.o `test -f 'tests/once-test.c' || echo './'`tests/once-test.c
tests/once-test.c:39: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘barrier’
tests/once-test.c: In function ‘thread_func’:
tests/once-test.c:66: warning: implicit declaration of function ‘pthread_barrier_wait’
tests/once-test.c:66: error: ‘barrier’ undeclared (first use in this function)
tests/once-test.c:66: error: (Each undeclared identifier is reported only once
tests/once-test.c:66: error: for each function it appears in.)
tests/once-test.c:67: error: ‘PTHREAD_BARRIER_SERIAL_THREAD’ undeclared (first use in this function)
tests/once-test.c: In function ‘main’:
tests/once-test.c:82: warning: implicit declaration of function ‘pthread_barrier_init’
tests/once-test.c:82: error: ‘barrier’ undeclared (first use in this function)
tests/once-test.c:106: warning: implicit declaration of function ‘pthread_barrier_destroy’
tests/once-test.c:39: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘barrier’
tests/once-test.c: In function ‘thread_func’:
tests/once-test.c:66: warning: implicit declaration of function ‘pthread_barrier_wait’
tests/once-test.c:66: error: ‘barrier’ undeclared (first use in this function)
tests/once-test.c:66: error: (Each undeclared identifier is reported only once
tests/once-test.c:66: error: for each function it appears in.)
tests/once-test.c:67: error: ‘PTHREAD_BARRIER_SERIAL_THREAD’ undeclared (first use in this function)
tests/once-test.c: In function ‘main’:
tests/once-test.c:82: warning: implicit declaration of function ‘pthread_barrier_init’
tests/once-test.c:82: error: ‘barrier’ undeclared (first use in this function)
tests/once-test.c:106: warning: implicit declaration of function ‘pthread_barrier_destroy’
lipo: can't open input file: /var/folders/zl/pt95hwl5347_d0t4y0xz6zz40000gn/T//cc8mJjCu.out (No such file or directory)
make[3]: **\* [once_test-once-test.o] Error 1
make[2]: **\* [install] Error 2
make[1]: **\* [install-recursive] Error 1
make: **\* [install] Error 2

**Comment by lhm** [comment]
I'm getting a somewhat similar error as well:

```

  CC       echo_cancel_test-module-echo-cancel.o
  CC       echo_cancel_test-adrian-aec.o
  CC       echo_cancel_test-adrian.o
  CC       echo_cancel_test-speex.o
  CC       echo_cancel_test-adrian-aec-orc-gen.o
  CXXLD    echo-cancel-test
ld: warning: in /opt/local/lib/libsamplerate.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /opt/local/lib/libwrap.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /opt/local/lib/libspeexdsp.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /opt/local/lib/liborc-0.4.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
Undefined symbols for architecture i386:
  "_speex_echo_state_init_mc", referenced from:
      _pa_speex_ec_init in echo_cancel_test-speex.o
  "_speex_preprocess_run", referenced from:
      _pa_speex_ec_run in echo_cancel_test-speex.o
  "_orc_program_set_backup_function", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_orc_program_append_2", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_orc_program_free", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_speex_preprocess_state_destroy", referenced from:
      _pa_speex_ec_done in echo_cancel_test-speex.o
      _pa_speex_ec_init in echo_cancel_test-speex.o
  "_orc_program_new", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_orc_program_add_source", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_orc_once_mutex_lock", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_orc_program_take_code", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_orc_program_add_destination", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_speex_preprocess_ctl", referenced from:
      _pa_speex_ec_init in echo_cancel_test-speex.o
      _pa_speex_ec_init in echo_cancel_test-speex.o
      _pa_speex_ec_init in echo_cancel_test-speex.o
      _pa_speex_ec_init in echo_cancel_test-speex.o
      _pa_speex_ec_init in echo_cancel_test-speex.o
  "_speex_echo_ctl", referenced from:
      _pa_speex_ec_init in echo_cancel_test-speex.o
  "_speex_echo_state_destroy", referenced from:
      _pa_speex_ec_done in echo_cancel_test-speex.o
  "_orc_program_set_name", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_orc_program_compile", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_orc_once_mutex_unlock", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_orc_program_add_temporary", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_speex_echo_cancellation", referenced from:
      _pa_speex_ec_run in echo_cancel_test-speex.o
  "_orc_program_add_parameter_float", referenced from:
      _update_tap_weights in echo_cancel_test-adrian-aec-orc-gen.o
  "_speex_preprocess_state_init", referenced from:
      _pa_speex_ec_init in echo_cancel_test-speex.o
ld: symbol(s) not found for architecture i386
collect2: ld returned 1 exit status
lipo: can't open input file: /var/folders/+a/+a2YOQAcHYav8OVjw-KhsE+++TI/-Tmp-//cc1c8biE.out (No such file or directory)
make[3]: *** [echo-cancel-test] Error 1
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

That is on 10.6.8, latest macports. Any ideas?
