### ISSUE TITLE
OSX building issue

### ISSUE THREAD

**Issue by emoret** [zonque/PulseAudioOSX#3]
I am now using git://anongit.freedesktop.org/pulseaudio/pulseaudio as this seems to be the new location of pulseaudio. Please tell me if I should use another branch. When I run ./deploy.sh, I receive the below message

In file included from pulse/glib-mainloop.c:34:
pulse/glib-mainloop.h:57: error: expected ')' before '_' token
pulse/glib-mainloop.c:40: error: expected specifier-qualifier-list before 'GPollFD'
pulse/glib-mainloop.c:78: error: expected specifier-qualifier-list before 'GSource'
pulse/glib-mainloop.c: In function 'cleanup_io_events':
pulse/glib-mainloop.c:96: error: 'pa_glib_mainloop' has no member named 'io_events'
pulse/glib-mainloop.c:98: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:100: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c:104: error: 'pa_glib_mainloop' has no member named 'io_events'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'prev'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'prev'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'prev'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'prev'
pulse/glib-mainloop.c:107: warning: implicit declaration of function 'g_assert'
pulse/glib-mainloop.c:107: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c:108: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c:111: error: 'pa_io_event' has no member named 'poll_fd_added'
pulse/glib-mainloop.c:112: warning: implicit declaration of function 'g_source_remove_poll'
pulse/glib-mainloop.c:112: error: 'pa_glib_mainloop' has no member named 'source'
pulse/glib-mainloop.c:112: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:114: error: 'pa_io_event' has no member named 'destroy_callback'
pulse/glib-mainloop.c:115: error: 'pa_io_event' has no member named 'destroy_callback'
pulse/glib-mainloop.c:115: error: 'pa_glib_mainloop' has no member named 'api'
pulse/glib-mainloop.c:115: error: 'pa_io_event' has no member named 'userdata'
pulse/glib-mainloop.c:123: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c: In function 'cleanup_time_events':
pulse/glib-mainloop.c:129: error: 'pa_glib_mainloop' has no member named 'time_events'
pulse/glib-mainloop.c:133: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c:137: error: 'pa_glib_mainloop' has no member named 'time_events'
pulse/glib-mainloop.c:140: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c:141: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c:145: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:146: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:150: error: 'pa_glib_mainloop' has no member named 'api'
pulse/glib-mainloop.c:158: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c: In function 'cleanup_defer_events':
pulse/glib-mainloop.c:164: error: 'pa_glib_mainloop' has no member named 'defer_events'
pulse/glib-mainloop.c:168: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c:172: error: 'pa_glib_mainloop' has no member named 'defer_events'
pulse/glib-mainloop.c:175: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c:176: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c:180: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:181: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:185: error: 'pa_glib_mainloop' has no member named 'api'
pulse/glib-mainloop.c:193: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c: At top level:
pulse/glib-mainloop.c:196: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'map_flags_to_glib'
pulse/glib-mainloop.c:204: error: expected ')' before 'flags'
pulse/glib-mainloop.c: In function 'glib_io_new':
pulse/glib-mainloop.c:233: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:234: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:234: warning: implicit declaration of function 'map_flags_to_glib'
pulse/glib-mainloop.c:235: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:237: error: 'pa_io_event' has no member named 'callback'
pulse/glib-mainloop.c:238: error: 'pa_io_event' has no member named 'userdata'
pulse/glib-mainloop.c:239: error: 'pa_io_event' has no member named 'destroy_callback'
pulse/glib-mainloop.c:241: error: 'pa_glib_mainloop' has no member named 'io_events'
pulse/glib-mainloop.c:241: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:241: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:241: error: 'pa_io_event' has no member named 'prev'
pulse/glib-mainloop.c:243: warning: implicit declaration of function 'g_source_add_poll'
pulse/glib-mainloop.c:243: error: 'pa_glib_mainloop' has no member named 'source'
pulse/glib-mainloop.c:243: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:244: error: 'pa_io_event' has no member named 'poll_fd_added'
pulse/glib-mainloop.c: In function 'glib_io_enable':
pulse/glib-mainloop.c:253: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c: In function 'glib_io_free':
pulse/glib-mainloop.c:261: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c:263: error: 'pa_io_event' has no member named 'poll_fd_added'
pulse/glib-mainloop.c:264: error: 'pa_glib_mainloop' has no member named 'source'
pulse/glib-mainloop.c:264: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:265: error: 'pa_io_event' has no member named 'poll_fd_added'
pulse/glib-mainloop.c: In function 'glib_io_set_destroy':
pulse/glib-mainloop.c:273: error: 'pa_io_event' has no member named 'destroy_callback'
pulse/glib-mainloop.c: In function 'glib_time_new':
pulse/glib-mainloop.c:299: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:301: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:302: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:304: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:305: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:313: error: 'pa_glib_mainloop' has no member named 'time_events'
pulse/glib-mainloop.c: In function 'glib_time_restart':
pulse/glib-mainloop.c:323: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:324: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:326: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:331: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:332: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:334: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:335: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:336: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:337: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c: In function 'glib_time_free':
pulse/glib-mainloop.c:345: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c:348: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:350: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:351: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c: In function 'glib_defer_new':
pulse/glib-mainloop.c:382: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:388: error: 'pa_glib_mainloop' has no member named 'defer_events'
pulse/glib-mainloop.c: In function 'glib_defer_enable':
pulse/glib-mainloop.c:397: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:398: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:400: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c: In function 'glib_defer_free':
pulse/glib-mainloop.c:410: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c:413: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:414: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c: In function 'glib_quit':
pulse/glib-mainloop.c:429: warning: implicit declaration of function 'g_warning'
pulse/glib-mainloop.c: In function 'find_next_time_event':
pulse/glib-mainloop.c:438: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:439: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:441: error: 'pa_glib_mainloop' has no member named 'time_events'
pulse/glib-mainloop.c:455: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c: In function 'scan_dead':
pulse/glib-mainloop.c:462: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c:465: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c:468: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c: At top level:
pulse/glib-mainloop.c:472: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'prepare_func'
pulse/glib-mainloop.c:507: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'check_func'
pulse/glib-mainloop.c:538: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'dispatch_func'
pulse/glib-mainloop.c:613: error: expected ')' before '_' token
pulse/glib-mainloop.c: In function 'pa_glib_mainloop_free':
pulse/glib-mainloop.c:653: warning: implicit declaration of function 'g_main_context_unref'
pulse/glib-mainloop.c:653: error: 'pa_glib_mainloop' has no member named 'context'
pulse/glib-mainloop.c:654: warning: implicit declaration of function 'g_source_destroy'
pulse/glib-mainloop.c:654: error: 'pa_glib_mainloop' has no member named 'source'
pulse/glib-mainloop.c:655: warning: implicit declaration of function 'g_source_unref'
pulse/glib-mainloop.c:655: error: 'pa_glib_mainloop' has no member named 'source'
pulse/glib-mainloop.c: In function 'pa_glib_mainloop_get_api':
pulse/glib-mainloop.c:661: error: 'pa_glib_mainloop' has no member named 'api'
pulse/glib-mainloop.c:33:18: error: glib.h: No such file or directory
In file included from pulse/glib-mainloop.c:34:
pulse/glib-mainloop.h:57: error: expected ')' before '_' token
pulse/glib-mainloop.c:40: error: expected specifier-qualifier-list before 'GPollFD'
pulse/glib-mainloop.c:78: error: expected specifier-qualifier-list before 'GSource'
pulse/glib-mainloop.c: In function 'cleanup_io_events':
pulse/glib-mainloop.c:96: error: 'pa_glib_mainloop' has no member named 'io_events'
pulse/glib-mainloop.c:98: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:100: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c:104: error: 'pa_glib_mainloop' has no member named 'io_events'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'prev'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'prev'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'prev'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:104: error: 'pa_io_event' has no member named 'prev'
pulse/glib-mainloop.c:107: warning: implicit declaration of function 'g_assert'
pulse/glib-mainloop.c:107: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c:108: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c:111: error: 'pa_io_event' has no member named 'poll_fd_added'
pulse/glib-mainloop.c:112: warning: implicit declaration of function 'g_source_remove_poll'
pulse/glib-mainloop.c:112: error: 'pa_glib_mainloop' has no member named 'source'
pulse/glib-mainloop.c:112: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:114: error: 'pa_io_event' has no member named 'destroy_callback'
pulse/glib-mainloop.c:115: error: 'pa_io_event' has no member named 'destroy_callback'
pulse/glib-mainloop.c:115: error: 'pa_glib_mainloop' has no member named 'api'
pulse/glib-mainloop.c:115: error: 'pa_io_event' has no member named 'userdata'
pulse/glib-mainloop.c:123: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c: In function 'cleanup_time_events':
pulse/glib-mainloop.c:129: error: 'pa_glib_mainloop' has no member named 'time_events'
pulse/glib-mainloop.c:133: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c:137: error: 'pa_glib_mainloop' has no member named 'time_events'
pulse/glib-mainloop.c:140: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c:141: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c:145: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:146: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:150: error: 'pa_glib_mainloop' has no member named 'api'
pulse/glib-mainloop.c:158: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c: In function 'cleanup_defer_events':
pulse/glib-mainloop.c:164: error: 'pa_glib_mainloop' has no member named 'defer_events'
pulse/glib-mainloop.c:168: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c:172: error: 'pa_glib_mainloop' has no member named 'defer_events'
pulse/glib-mainloop.c:175: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c:176: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c:180: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:181: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:185: error: 'pa_glib_mainloop' has no member named 'api'
pulse/glib-mainloop.c:193: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c: At top level:
pulse/glib-mainloop.c:196: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'map_flags_to_glib'
pulse/glib-mainloop.c:204: error: expected ')' before 'flags'
pulse/glib-mainloop.c: In function 'glib_io_new':
pulse/glib-mainloop.c:233: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:234: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:234: warning: implicit declaration of function 'map_flags_to_glib'
pulse/glib-mainloop.c:235: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:237: error: 'pa_io_event' has no member named 'callback'
pulse/glib-mainloop.c:238: error: 'pa_io_event' has no member named 'userdata'
pulse/glib-mainloop.c:239: error: 'pa_io_event' has no member named 'destroy_callback'
pulse/glib-mainloop.c:241: error: 'pa_glib_mainloop' has no member named 'io_events'
pulse/glib-mainloop.c:241: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:241: error: 'pa_io_event' has no member named 'next'
pulse/glib-mainloop.c:241: error: 'pa_io_event' has no member named 'prev'
pulse/glib-mainloop.c:243: warning: implicit declaration of function 'g_source_add_poll'
pulse/glib-mainloop.c:243: error: 'pa_glib_mainloop' has no member named 'source'
pulse/glib-mainloop.c:243: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:244: error: 'pa_io_event' has no member named 'poll_fd_added'
pulse/glib-mainloop.c: In function 'glib_io_enable':
pulse/glib-mainloop.c:253: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c: In function 'glib_io_free':
pulse/glib-mainloop.c:261: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c:263: error: 'pa_io_event' has no member named 'poll_fd_added'
pulse/glib-mainloop.c:264: error: 'pa_glib_mainloop' has no member named 'source'
pulse/glib-mainloop.c:264: error: 'pa_io_event' has no member named 'poll_fd'
pulse/glib-mainloop.c:265: error: 'pa_io_event' has no member named 'poll_fd_added'
pulse/glib-mainloop.c: In function 'glib_io_set_destroy':
pulse/glib-mainloop.c:273: error: 'pa_io_event' has no member named 'destroy_callback'
pulse/glib-mainloop.c: In function 'glib_time_new':
pulse/glib-mainloop.c:299: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:301: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:302: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:304: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:305: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:313: error: 'pa_glib_mainloop' has no member named 'time_events'
pulse/glib-mainloop.c: In function 'glib_time_restart':
pulse/glib-mainloop.c:323: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:324: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:326: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:331: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:332: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:334: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:335: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:336: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:337: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c: In function 'glib_time_free':
pulse/glib-mainloop.c:345: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c:348: error: 'pa_glib_mainloop' has no member named 'n_enabled_time_events'
pulse/glib-mainloop.c:350: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:351: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c: In function 'glib_defer_new':
pulse/glib-mainloop.c:382: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:388: error: 'pa_glib_mainloop' has no member named 'defer_events'
pulse/glib-mainloop.c: In function 'glib_defer_enable':
pulse/glib-mainloop.c:397: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:398: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:400: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c: In function 'glib_defer_free':
pulse/glib-mainloop.c:410: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c:413: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c:414: error: 'pa_glib_mainloop' has no member named 'n_enabled_defer_events'
pulse/glib-mainloop.c: In function 'glib_quit':
pulse/glib-mainloop.c:429: warning: implicit declaration of function 'g_warning'
pulse/glib-mainloop.c: In function 'find_next_time_event':
pulse/glib-mainloop.c:438: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:439: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c:441: error: 'pa_glib_mainloop' has no member named 'time_events'
pulse/glib-mainloop.c:455: error: 'pa_glib_mainloop' has no member named 'cached_next_time_event'
pulse/glib-mainloop.c: In function 'scan_dead':
pulse/glib-mainloop.c:462: error: 'pa_glib_mainloop' has no member named 'io_events_please_scan'
pulse/glib-mainloop.c:465: error: 'pa_glib_mainloop' has no member named 'time_events_please_scan'
pulse/glib-mainloop.c:468: error: 'pa_glib_mainloop' has no member named 'defer_events_please_scan'
pulse/glib-mainloop.c: At top level:
pulse/glib-mainloop.c:472: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'prepare_func'
pulse/glib-mainloop.c:507: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'check_func'
pulse/glib-mainloop.c:538: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'dispatch_func'
pulse/glib-mainloop.c:613: error: expected ')' before '_' token
pulse/glib-mainloop.c: In function 'pa_glib_mainloop_free':
pulse/glib-mainloop.c:653: warning: implicit declaration of function 'g_main_context_unref'
pulse/glib-mainloop.c:653: error: 'pa_glib_mainloop' has no member named 'context'
pulse/glib-mainloop.c:654: warning: implicit declaration of function 'g_source_destroy'
pulse/glib-mainloop.c:654: error: 'pa_glib_mainloop' has no member named 'source'
pulse/glib-mainloop.c:655: warning: implicit declaration of function 'g_source_unref'
pulse/glib-mainloop.c:655: error: 'pa_glib_mainloop' has no member named 'source'
pulse/glib-mainloop.c: In function 'pa_glib_mainloop_get_api':
pulse/glib-mainloop.c:661: error: 'pa_glib_mainloop' has no member named 'api'
lipo: can't open input file: /var/folders/n8/p84dp74x6vjbg240qt9hc5hh0000gn/T//ccPOMy43.out (No such file or directory)
make[3]: **\* [libpulse_mainloop_glib_la-glib-mainloop.lo] Error 1
make[2]: **\* [install] Error 2
make[1]: **\* [install-recursive] Error 1
make: **\* [install] Error 2

**Comment by zonque** [comment]
On 07.10.11 12:28, emoret wrote:

> I am now using git://anongit.freedesktop.org/pulseaudio/pulseaudio as this seems to be the new location of pulseaudio. Please tell me if I should use another branch. When I run ./deploy.sh, I receive the below message
> 
> In file included from pulse/glib-mainloop.c:34:
> pulse/glib-mainloop.h:57: error: expected ')' before '*' token
> [...]

Strange. The glib foo should not be built at all. In my script 
build_pulseaudio.sh, there is an explicit directive "--disable-glib2" 
which should switch off all glib related code.

Anyway - I'm currently working on this project again, and I might come 
up with binary relases any time soon.

But let me know when you solved this issue :)

Daniel
