### ISSUE TITLE
Problems compiling on OS X Lion 10.7.3

### ISSUE THREAD

**Issue by moonman** [zonque/PulseAudioOSX#6]
Hello,

I am having trouble compiling this on Lion:

checking looking for Apple CoreService Framework... checking /Developer/Headers/FlatCarbon/CoreServices.h usability... no
checking /Developer/Headers/FlatCarbon/CoreServices.h presence... no
checking for /Developer/Headers/FlatCarbon/CoreServices.h... no
configure: error: CoreServices.h header file not found

I did find the file in /System/Library/Frameworks/CoreServices.framework/Headers, however for some reason the script doesn't find it. Any help would be appreciated.

**Comment by moonman** [comment]
Running on MacMini Late 2009. MacPorts 2.0.4. I did have to create a symlink for gcc-4.2 as it couldn't find gcc without it.

**Comment by zonque** [comment]
Sorry, I cannot currently keep up with maintainance of this project. Also, I never tried to compile the sources on Lion. So please, if you find a way to fix this behaviour, consider sending me a pull request. Thanks!

**Comment by moonman** [comment]
I guess I will try to compile on OSX 10.6 and then install the package on 10.7. I dunno how it will work though as macports is compile on 10.7 from scratch....
