### ISSUE TITLE
Nothing in $PATH, missing doc and deps

### ISSUE THREAD

**Issue by tkuther** [zonque/PulseAudioOSX#7]
Hi,

I'm trying to get this running in my 10.6.8 install.

1) Please add "check" and "pkgconfig" to the MacPorts dependencies list.
2) Please mention in the source compilation wiki that Growl.framework needs to be copied to /Library/Frameworks (I used 1.2.2 Growl and Growl-SDK found on their code.google.com page, SDK 2.0 doesn't work on Snow Leo it sems)

With that I got the package to built and installed it.

Now I miss all pulseaudio binaries in my $PATH. Do I have to set that myself ,like
`defaults write $HOME/.MacOSX/environment PATH "$PATH:/Library/Frameworks/PulseAudio.framework/Contents/MacOS/bin`
?

I ask because autostart at Login does not work, and so I cannot connect any server in PulseConsole.

**Comment by zonque** [comment]
Hi,

I'm not currently working on this project anymore, as my Mac died on me some months ago. So unfortunately, I can't help you with that. If you have any improvements, please fork the project and send me a pull request.
