### ISSUE TITLE
gcc-4.2 no longer exists in OS X Mountain Lion

### ISSUE THREAD

**Issue by spitfire** [zonque/PulseAudioOSX#8]
In Mountain Lion, (with Xcode 4.5, and command-line tools installed) gcc-4.2 command does not exist. Please adapt the build script to either use 'gcc' or 'clang'

**Comment by zonque** [comment]
Please send a patch.

**Comment by spitfire** [comment]
I'll fork it, modify file, and send a merge request, ok?

**Comment by zonque** [comment]
Yes, please do. I currently don't have any time to further maintain this piece of software, and I don't have a current version of OSX either. So I rely on other people. Feel free to also continue development if you're into it :)
